apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: llama-3-1-8b-instruct-distributed
  annotations:
    opendatahub.io/model-type: generative
    openshift.io/display-name: distributed/Llama-3.1-8B-Instruct
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-name: nvidia-gpu-serving
spec:
  replicas: 0
  model:
    uri: 'oci://registry.redhat.io/rhelai1/modelcar-llama-3-1-8b-instruct:1.5'
    name: llama-3-1-8b-instruct
  router:
    route: {}
    gateway: {}
    scheduler: {}
  template:
    containers:
      - name: main
        env:
          - name: VLLM_ADDITIONAL_ARGS
            value: "--dtype=half --max-model-len=20000 --gpu-memory-utilization=0.95 --enable-auto-tool-choice --tool-call-parser=llama3_json --chat-template=/opt/app-root/template/tool_chat_template_llama3.2_json.jinja"
        resources:
          limits:
            cpu: '4'
            memory: 12Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '4'
            memory: 8Gi
            nvidia.com/gpu: '1'
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 180
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 5
    tolerations:
      - effect: NoSchedule
        key: nvidia-gpu-only
        operator: Exists
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists