kind: ConfigMap
apiVersion: v1
metadata:
  name: chatbot-ui-config
  namespace: proposal-rh-ai
data:
  AGENT_INSTRUCTIONS: |
    You are a helpful assistant.
    You can use the tools available to answer user questions.
    IMPORTANT: You can only use one tool at a time. 
    Do not attempt to call multiple tools in a single response