kind: Deployment
apiVersion: apps/v1
metadata:
  name: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
        - name: chatbot-ui
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: API_KEY
              value: 'fake-key'
            - name: APP_LOG_LEVEL
              value: 'DEBUG'
            - name: MODEL_ID
              value: 'vllm-inference/redhataillama-31-8b-instruct'
            - name: LLAMA_STACK_BASE_URL
              value: 'http://llama-stack-milvus-remote-service.proposal-rh-ai.svc.cluster.local:8321/v1'
            - name: TEMPERATURE
              value: '0.95'
            - name: TOP_P
              value: '0.95'
            - name: MAX_TOKENS
              value: '4096'
            - name: EMBEDDING_MODEL
              value: 'sentence-transformers/ibm-granite/granite-embedding-125m-english'
            - name: MILVUS_HOST
              value: 'milvus-service.proposal-rh-ai.svc.cluster.local'
            - name: MILVUS_PORT
              value: '19530'
            - name: VECTOR_DB_NAME_OCP
              value: 'skus_rh_vector_db'
            - name: COORDINATOR_AGENT_INSTRUCTIONS
              valueFrom:
                configMapKeyRef:
                  name: chatbot-ui-config
                  key: COORDINATOR_AGENT_INSTRUCTIONS
            - name: COORDINATOR_AGENT_DELEGATOR_PROMPT
              valueFrom:
                configMapKeyRef:
                  name: chatbot-ui-config
                  key: COORDINATOR_AGENT_DELEGATOR_PROMPT
            - name: SKUS_AGENT_INSTRUCTIONS
              valueFrom:
                configMapKeyRef:
                  name: chatbot-ui-config
                  key: SKUS_AGENT_INSTRUCTIONS
            - name: INFRAESTRUCTURE_AGENT_INSTRUCTIONS
              valueFrom:
                configMapKeyRef:
                  name: chatbot-ui-config
                  key: INFRAESTRUCTURE_AGENT_INSTRUCTIONS
          ports:
            - containerPort: 7861
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'quay.io/lcoronad/chatbot-proposal-ai:1.1.5'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      serviceAccountName: chatbot-ui
      serviceAccount: chatbot-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
