apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcp-slack
spec:
  to:
    kind: Service
    name: mcp-slack
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
