apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - qwen3-coder-480b-serving-runtime.yaml
  - qwen3-coder-480b-secret.yaml
  - qwen3-coder-480b-inference-service.yaml
  - qwen3-coder-480b-pvc.yaml