apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-coder-480b-pvc
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi