kind: Secret
apiVersion: v1
metadata:
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/display-name: qwen3-coder-480b-secret
  name: qwen3-coder-480b-secret
  labels:
    opendatahub.io/dashboard: 'true'
stringData:
  URI: oci://registry.redhat.io/rhelai1/modelcar-qwen3-coder-480b-a35b-instruct-fp8:1.5
type: Opaque