apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-inference-model-secret
type: Opaque
stringData:
  INFERENCE_MODEL: publishers/llm/models/llama-3-1-8b-instruct
  VLLM_URL: https://maas.apps.cluster-nrhln.nrhln.sandbox1257.opentlc.com/v1
  VLLM_TLS_VERIFY: 'sk-oai-PTk3IiNYDWp2LxrS_NTziSsez3P69GG67gClPsWN6XUtLVmBo4Gh1kkuXri3'
  VLLM_API_TOKEN: temporary-token