apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-db-secret
  namespace: proposal-rh-ai
type: Opaque
stringData:
  POSTGRES_HOST: "postgresql-llama-stack.proposal-rh-ai.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "userllamastack"
  POSTGRES_PASSWORD: "RedHat2026!"
  POSTGRES_DB: "llamastackdb"