apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-inference-model-secret
  namespace: proposal-rh-ai
type: Opaque
stringData:
  INFERENCE_MODEL: redhataillama-31-8b-instruct
  VLLM_URL: http://redhataillama-31-8b-instruct-predictor.proposal-rh-ai.svc.cluster.local/v1
  VLLM_TLS_VERIFY: 'false'