kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: milvus-pvc
  namespace: proposal-rh-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem