apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consume-agent-task
spec:
  workspaces:
    - name: source-dir
  params:
    - name: repo-path
    - name: pull-request-number
    - name: api-url
    - name: repo-owner
    - name: commit-id
  steps:
    - name: consume-agent
      image: image-registry.openshift-image-registry.svc:5000/triage-analysis-sast/consume-agent:1.0.1
      workingDir: $(workspaces.source-dir.path)
      script: |
        #!/bin/sh
        cd $(workspaces.source-dir.path)
        
        [ -f trivy-results.json ] || echo "{}" > trivy-results.json
        [ -f opengrep-results.sarif ] || echo "{}" > opengrep-results.sarif

        jq -n \
          --arg repo "$(params.repo-path)" \
          --arg pr "$(params.pull-request-number)" \
          --arg repo_owner "$(params.repo-owner)" \
          --arg commit_id "$(params.commit-id)" \
          --slurpfile trivy trivy-results.json \
          --slurpfile opengrep opengrep-results.sarif \
          '{"repo_path": $repo, "pull_request_number": $pr, "repo_owner": $repo_owner, "commit_id": $commit_id, "trivy_json": [ $trivy[0].Results[]? | .Vulnerabilities[]? | { "id": .VulnerabilityID, "pkg": .PkgName, "fixed": .FixedVersion } ], "opengrep_sarif": [ $opengrep[0].runs[]?.results[]? | { "ruleId": .ruleId, "file": .locations[0].physicalLocation.artifactLocation.uri, "line": .locations[0].physicalLocation.region.startLine } ]}' \
          > payload.json
        
        cat payload.json

        curl -s -X POST -H "Content-Type: application/json" -d @payload.json \
          "$(params.api-url)"