apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - trivy-scan-task.yaml
  - opengrep-scan-task.yaml
  - consume-agent-task.yaml
  - analysis-security-pipeline.yaml
  - analysis-security-pipeline-template.yaml
  - github-pr-binding.yaml
  - github-pr-listener.yaml