apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy-scan-task
spec:
  workspaces:
    - name: source-dir
  steps:
    - name: trivy-scan
      env:
        - name: TRIVY_CACHE_DIR
          value: "$(workspaces.source-dir.path)/.trivy-cache"
        - name: HOME
          value: "$(workspaces.source-dir.path)"
      image: aquasec/trivy:latest
      workingDir: $(workspaces.source-dir.path)
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: { drop: ["ALL"] }
        runAsNonRoot: true
        runAsUser: 1001
      script: |
        #!/bin/sh
        trivy fs --format json --output $(workspaces.source-dir.path)/trivy-results.json . || true