apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: triage-analysis-sast-dev

resources:
  - ../../base

patches:
  - path: patch-path-health-check.yaml
    target:
      group: kubeflow.org
      kind: Notebook
      version: v1
  - path: patch-env-notebook-args.yaml
    target:
      group: kubeflow.org
      kind: Notebook
      version: v1