apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proposal-rh-ai

resources:
  - standard-workbench-pvc.yaml
  - minio-data-connection.yaml
  - standard-workbench-notebook.yaml
  - standard-workbench-sa.yaml
  - standard-workbench-kube-rbac-proxy-service.yaml
  - standard-workbench-rbac-configmap.yaml
  - standard-workbench-service.yaml