apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-inference-model-secret
type: Opaque
stringData:
  INFERENCE_MODEL: redhatqwen-3-coder-480b
  VLLM_URL: http://redhatqwen-3-coder-480b-predictor.triage-analysis-sast.svc.cluster.local/v1
  VLLM_TLS_VERIFY: 'false'
  VLLM_API_TOKEN: temporary-token