apiVersion: dscinitialization.opendatahub.io/v2
kind: DSCInitialization
metadata:
  name: default-dsci
spec:
  applicationsNamespace: redhat-ods-applications
  monitoring:
    managementState: Managed
    metrics:
      replicas: 1
      resources:
        cpulimit: 500m
        cpurequest: 100m
        memorylimit: 512Mi
        memoryrequest: 256Mi
      storage:
        size: 5Gi
        retention: 90d
    namespace: redhat-ods-monitoring
    traces:
      sampleRatio: '0.1'
      storage:
        backend: pv
        retention: 2160h
  trustedCABundle:
    customCABundle: ''
    managementState: Managed
