apiVersion: v1
kind: Namespace
metadata:
  name: triage-analysis-sast
  labels:
    opendatahub.io/dashboard: "true"
    kubernetes.io/metadata.name: triage-analysis-sast
    modelmesh-enabled: "true"