apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: kuadrant-system
spec:
  clusterWide: true
  replicas: 1
  listener:
    tls:
      enabled: true
      certSecretRef:
        name: authorino-server-cert
  volumes:
    defaultMode: 420
    items:
      - configMaps:
          - openshift-service-ca.crt
        mountPath: /etc/pki/tls/certs/maas-ca
        name: openshift-service-ca
  oidcServer:
    tls:
      enabled: false